=== L0uchz/stb23v1/src/main/resources/stb23.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://univrouen.fr/stb23"
	targetNamespace="http://univrouen.fr/stb23"
	elementFormDefault="unqualified">

<!-- Element Racine -->
<xs:element name="stb" type="stbType"/>

<!-- ComplexType -->
<xs:complexType name="stbType">
	<xs:sequence>
		<xs:element name="title" type="restrictedString128" minOccurs="1" maxOccurs="1" default="STB 23"/>
		<xs:element name="version" type="restrictedDecimalMin0.1" minOccurs="1" maxOccurs="1" default="0.1"/>
		<xs:element name="date" type="xs:date" minOccurs="1" maxOccurs="1"/>
		<xs:element name="description" type="restrictedString128" minOccurs="1" maxOccurs="1"/>
		<xs:element name="client" type="clientType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="team" type="teamType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="features" type="featuresType" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="clientType">
	<xs:sequence>
		<xs:element name="entity" type="restrictedString32" minOccurs="1" maxOccurs="1"/>
		<xs:element name="person" type="personType"></xs:element>
		<xs:choice>
			<xs:element name="mail" type="mailType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="tel" type="telType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="teamType">
	<xs:sequence>
		<xs:element name="member" type="memberType" minOccurs="2" maxOccurs="8"/>
	</xs:sequence>
</xs:complexType>

	
<xs:complexType name="featuresType">
	<xs:sequence>
		<xs:element name="feature" type="featureType" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="personType">
	<xs:sequence>
		<xs:element name="nom" type="restrictedString32" minOccurs="1" maxOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="gender" type="genderType" use="optional"/>
	<xs:attribute name="lastname" type="restrictedString32" use="required"/>
</xs:complexType>


<xs:complexType name="memberType">
	<xs:sequence>
		<xs:element name="person" type="personType"></xs:element>
		<xs:element name="mail" type="mailType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="function" type="restrictedString128" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="featureType">
	<xs:sequence>
		<xs:element name="description" type="restrictedString128" minOccurs="1" maxOccurs="1"/>
		<xs:element name="priority" type="priorityType" minOccurs="1" maxOccurs="1"/>
		<xs:element name="delivery" type="xs:date" minOccurs="0" maxOccurs="1"/>
		<xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
	<xs:attribute name="name" type="restrictedString32" use="required"/>
	<xs:attribute name="section" type="xs:int" use="required"/>
	<xs:attribute name="number" type="xs:int" use="required"/>
</xs:complexType>

<!-- SimpleType -->

<xs:simpleType name="restrictedString128">
	<xs:restriction base="xs:string">
		<xs:maxLength value="128"></xs:maxLength>
		<xs:pattern value="[^\.\-_]+"></xs:pattern>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="restrictedDecimalMin0.1">
	<xs:restriction base="xs:decimal">
		<xs:minInclusive value="0.1"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="restrictedString32">
	<xs:restriction base="xs:string">
		<xs:maxLength value="32"></xs:maxLength>
		<xs:pattern value="[^\.,&amp;:;~@()#!?$*=_]+"></xs:pattern> 
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="mailType">
	<xs:restriction base="xs:string">
		<xs:pattern value="[0-9a-zA-Z]+([-.][0-9a-zA-Z]+)*@[0-9a-zA-Z]+([-.][0-9a-zA-Z]+)*\.[a-zA-Z]{2,3}"></xs:pattern> 
	</xs:restriction>
</xs:simpleType>
	
<xs:simpleType name="telType">
	<xs:restriction base="xs:string">
		<xs:pattern value="\d{10}|(\d{2}\s){5}|[0]\s(\d{3}\s){3}|(\+33)\s\d\s(\d{2}\s){4}"></xs:pattern>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="genderType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="M."></xs:enumeration>
		<xs:enumeration value="Mme"></xs:enumeration>
		<xs:enumeration value="Miss"></xs:enumeration>
		<xs:enumeration value="Mrs"></xs:enumeration>
		<xs:enumeration value="Mr"></xs:enumeration>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="priorityType">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="0"></xs:minInclusive>
		<xs:maxInclusive value="10"></xs:maxInclusive>
	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== L0uchz/stb23v1/ressources/maximal.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:stb xmlns:p="http://univrouen.fr/stb23" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univrouen.fr/stb23 ../src/main/resources/stb23.xsd ">
    <title>STB 23 maxiamal</title>
    <version>0.2</version>
    <date>2023-02-15</date>
    <description>Fichier de test valide</description>
    <client>
        <entity>Mark 3</entity>
        <person lastname="Fabrice" gender="M.">
            <nom>Martin</nom>
        </person>
        <tel>0123456789</tel>
    </client>
    <team>
        <member>
            <person lastname="A" gender="Mrs">
                <nom>Albert</nom>
            </person>
            <mail>albert.test@mail.com</mail>
            <function>Chef de projet</function>
            <function>développeur</function>
        </member>
        <member>
            <person lastname="B" gender="Mr">
                <nom>Bastien</nom>
            </person>
            <mail>bastientesteur@test.fr</mail>
            <function>testeur</function>
        </member>
        <member>
            <person lastname="C"  gender="Mme">
                <nom>Charlyne</nom>
            </person>
            <mail>charlyne-test@test56.Com</mail>
            <function>QA</function>
            <function>testeuse</function>
        </member>
        <member>
            <person lastname="D" gender="Miss">
                <nom>Adams</nom>
            </person>
            <mail>albert.adams@example.com</mail>
            <function>développeuse</function>
        </member>
        <member>
            <person lastname="E" gender="M.">
                <nom>Anderson</nom>
            </person>
            <mail>Andersontest@mail.com</mail>
            <function>Analyste fonctionnel</function>
        </member>
        <member>
            <person lastname="F" gender="M.">
                <nom>Allen</nom>
            </person>
            <mail>allen.test@mail.com</mail>
            <function>Ingénieur DevOps</function>
        </member>
        <member>
            <person lastname="G" gender="Mrs">
                <nom>Mathias</nom>
            </person>
            <mail>Mathias.test@mail.com</mail>
            <function>Responsable de la documentation technique</function>
        </member>
        <member>
            <person lastname="H" gender="Mr">
                <nom>Archer</nom>
            </person>
            <mail>archer.test@mail.com</mail>
            <function>Administrateur système</function>
        </member>


    </team>
    <features>
        <feature name="debug" number="15" section="3">
            <description>Enlever les bugs de l'application</description>
            <priority>8</priority>
            <delivery>2023-02-23</delivery>
            <comment>a faire au plus vite</comment>
        </feature>
    </features>
</p:stb>

=== L0uchz/stb23v1/ressources/minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:stb xmlns:p="http://univrouen.fr/stb23" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univrouen.fr/stb23 ../src/main/resources/stb23.xsd ">
    <title>STB 23 minimal</title>
    <version>0.1</version>
    <date>2001-01-01</date>
    <description>Fichier de test valide</description>
    <client>
        <entity>entity</entity>
        <person lastname="deku">
            <nom>Antoine</nom>
        </person>
        <mail>Antoine@fac.com</mail>
    </client>
    <team>
        <member>
            <person lastname="Bozo">
                <nom>Nicolas</nom>
            </person>
            <mail>Nicolas51@bozo.fr</mail>
            <function>DÃ©veloppeur </function>
        </member>
        <member>
            <person lastname="Jim">
                <nom>CHEF</nom>
            </person>
            <mail>JIM.chef@test4.com</mail>
            <function>Architecte logiciel</function>
        </member>
    </team>
    <features>
        <feature name="Type" number="5" section="3">
            <description>description</description>
            <priority>0</priority>
        </feature>
    </features>
</p:stb>
